version: 2.1
jobs:
    build:
        docker:
          - image: python:3.7.3-stretch
        working_directory: ~/repo

        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "project-ml-microservice-kubernetes/requirements.txt" }}
# fallback to using the latest cache if no exact match is found
                - v1-dependencies-

          - run:
              name: install dependencies
              command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pwd
                    cd /root/repo/project-ml-microservice-kubernetes
                    make install
                    # Install hadolint
                    pwd
                    wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                    chmod +x hadolint
                    pwd
                    ls -lrt
    
          - save_cache:
              paths:
                - ./venv
              key: v1-dependencies-{{ checksum "project-ml-microservice-kubernetes/requirements.txt" }}

          - run:
              name: run lint
              command: |
                    . venv/bin/activate
                    pwd
                    cd /root/repo/project-ml-microservice-kubernetes
                    make lint
        
workflows:
  default:
    jobs:
      - build
